WebMotors/source/WebMotors.Web/Models/ErrorViewModel.cs
using System;

namespace WebMotors.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebMotors/source/WebMotors.Web/Controllers/AnuncioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebMotors.Core.Application;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMotors.Core.Entidades;
using System.Collections.Generic;

namespace WebMotors.Web.Controllers
{
    public class AnuncioController : Controller
    {
        private readonly IAnuncioApplication anuncioApplication;
        public AnuncioController(IAnuncioApplication anuncioApplication)
        {
            this.anuncioApplication = anuncioApplication;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var anuncios = await anuncioApplication.ObterTodos();

                return View(anuncios);
            }
            catch (System.Exception)
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cadastrar()
        {
            try
            {
                var marcas = await anuncioApplication.ObterMarcas();
                ViewBag.ListaDeMarcas = marcas.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });
            }
            catch (System.Exception)
            {
                //TODO tratar exceção e logar erro.
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(Anuncio anuncio)
        {
            try
            {
                Dictionary<string, string> erros = await anuncioApplication.Incluir(anuncio);

                if (erros.Any())
                {
                    foreach (var item in erros)
                    {
                        ModelState.AddModelError(item.Key, item.Value);
                    }

                    var marcas = await anuncioApplication.ObterMarcas();
                    ViewBag.ListaDeMarcas = marcas.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                    var modelos = await anuncioApplication.ObterModelosPorMarca(anuncio.MarcaId);
                    ViewBag.ListaDeModelos = modelos.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                    var versoes = await anuncioApplication.ObterVersoesPorModelo(anuncio.ModeloId);
                    ViewBag.ListaDeVersoes = versoes.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                    return View(anuncio);
                }

            }
            catch (System.Exception)
            {
                ModelState.AddModelError("", "Ocorreu um erro inesperado.");
                return View();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Atualizar(int id)
        {
            try
            {
                var anuncio = await anuncioApplication.ObterPorId(id);

                var marcas = await anuncioApplication.ObterMarcas();
                var marca = marcas.FirstOrDefault(m => m.Name == anuncio.Marca);
                ViewBag.ListaDeMarcas = marcas.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                var modelos = await anuncioApplication.ObterModelosPorMarca(marca.ID);
                var modelo = modelos.FirstOrDefault(m => m.Name == anuncio.Modelo);
                ViewBag.ListaDeModelos = modelos.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                var versoes = await anuncioApplication.ObterVersoesPorModelo(modelo.ID);
                var versao = versoes.FirstOrDefault(m => m.Name == anuncio.Versao);
                ViewBag.ListaDeVersoes = versoes.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                anuncio.MarcaId = marca.ID;
                anuncio.ModeloId = modelo.ID;
                anuncio.VersaoId = versao.ID;

                return View(anuncio);
            }
            catch (System.Exception)
            {
                ModelState.AddModelError("", "Ocorreu um erro inesperado.");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Atualizar(Anuncio anuncio)
        {
            try
            {
                Dictionary<string, string> erros = await anuncioApplication.Atualizar(anuncio);

                if (erros.Any())
                {
                    foreach (var item in erros)
                    {
                        ModelState.AddModelError(item.Key, item.Value);
                    }

                    var marcas = await anuncioApplication.ObterMarcas();
                    ViewBag.ListaDeMarcas = marcas.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                    var modelos = await anuncioApplication.ObterModelosPorMarca(anuncio.MarcaId);
                    ViewBag.ListaDeModelos = modelos.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                    var versoes = await anuncioApplication.ObterVersoesPorModelo(anuncio.ModeloId);
                    ViewBag.ListaDeVersoes = versoes.Select(m => new SelectListItem { Text = m.Name, Value = m.ID.ToString() });

                    return View(anuncio);
                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError("", "Ocorreu um erro inesperado.");
                return View();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Remover(int id)
        {
            try
            {
                var anuncio = await anuncioApplication.ObterPorId(id);
                return View(anuncio);
            }
            catch (System.Exception)
            {
                ModelState.AddModelError("", "Ocorreu um erro inesperado.");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Remover(Anuncio anuncio)
        {
            try
            {
                Dictionary<string, string> erros = await anuncioApplication.Remover(anuncio);

                if (erros.Any())
                {
                    foreach (var item in erros)
                    {
                        ModelState.AddModelError(item.Key, item.Value);
                    }

                    return View(anuncio);
                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError("", "Ocorreu um erro inesperado.");
                return View();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ObterModelos(int MarcaId)
        {
            var modelos = await anuncioApplication.ObterModelosPorMarca(MarcaId);

            return Json(new { modelos });
        }

        [HttpGet]
        public async Task<IActionResult> ObterVersoes(int ModeloId)
        {
            var versoes = await anuncioApplication.ObterVersoesPorModelo(ModeloId);

            return Json(new { versoes });
        }
    }
}

WebMotors/source/WebMotors.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebMotors.Web.Models;

namespace WebMotors.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebMotors/source/WebMotors.Web/Views/Anuncio/Atualizar.cshtml
@model Anuncio
@{
    ViewData["Title"] = "Atualizar Veículo";
}

@if (Model != null)
{

    <h1>Atualizar Veículo</h1>
    <form asp-action="Atualizar" method="post">
        <input type="hidden" asp-for="Id"/>
        <hr />

        <div class="row">
            <div class="form-group">
                @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    <select class="form-control" asp-for="MarcaId" asp-items="ViewBag.ListaDeMarcas">
                        <option value="-1">Selecione...</option>
                    </select>
                    <span asp-validation-for="MarcaId"></span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @if (ViewBag.ListaDeModelos != null)
                    {
                        <select class="form-control" asp-for="ModeloId" asp-items="ViewBag.ListaDeModelos">
                        </select>
                    }
                    else
                    {
                        <select class="form-control" asp-for="ModeloId">
                            <option value="-1">Selecione...</option>
                        </select>
                    }

                    <span asp-validation-for="ModeloId"></span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Versao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @if (ViewBag.ListaDeVersoes != null)
                    {
                        <select class="form-control" asp-for="VersaoId" asp-items="ViewBag.ListaDeVersoes">
                        </select>
                    }
                    else
                    {
                        <select class="form-control" asp-for="VersaoId">
                            <option value="-1">Selecione...</option>
                        </select>
                    }
                    <span asp-validation-for="VersaoId"></span>

                </div>
            </div>
        </div>

        <br />
        <br />
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Ano</label>
                    <input class="form-control" type="text" asp-for="Ano" placeholder="Ano" />
                    <span asp-validation-for="Ano" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label>Quilômetragem </label>
                    <input class="form-control" type="text" asp-for="Quilometragem" placeholder="Quilômetragem" />
                    <span asp-validation-for="Quilometragem" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label>Observação</label>
                    <input class="form-control" type="text" asp-for="Observacao" placeholder="Observação" />
                    <span asp-validation-for="Observacao" class="text-danger"></span>
                </div>
            </div>
        </div>

        <input type="submit" value="Salvar" class="btn btn-success" style="float:right; margin-left:10px;" />
        <a href="@Url.Action("Index", "Anuncio")" class="btn btn-danger" style="float:right">Cancelar </a>

        <input type="hidden" id="Marca" asp-for="Marca" />
        <input type="hidden" id="Modelo" asp-for="Modelo" />
        <input type="hidden" id="Versao" asp-for="Versao" />
    </form>
}
else
{
    <h5>Anúncio não encontrado</h5>
}

WebMotors/source/WebMotors.Web/Views/Anuncio/Cadastrar.cshtml
@model WebMotors.Core.Entidades.Anuncio

@{
    ViewData["Title"] = "Anunciar Veículo";
}

<h1>Anunciar Veículo</h1>
<form asp-action="Cadastrar" method="post">
    <hr />
    <div class="row">
        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                <select class="form-control" asp-for="MarcaId" asp-items="ViewBag.ListaDeMarcas">
                    <option value="-1">Selecione...</option>
                </select>
                <span asp-validation-for="MarcaId"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @if (ViewBag.ListaDeModelos != null)
                {
                    <select class="form-control" asp-for="ModeloId" asp-items="ViewBag.ListaDeModelos">
                    </select>
                }
                else
                {
                    <select class="form-control" asp-for="ModeloId">
                        <option value="-1">Selecione...</option>
                    </select>
                }

                <span asp-validation-for="ModeloId"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Versao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @if (ViewBag.ListaDeVersoes != null)
                {
                    <select class="form-control" asp-for="VersaoId" asp-items="ViewBag.ListaDeVersoes">
                    </select>
                }
                else
                {
                    <select class="form-control" asp-for="VersaoId">
                        <option value="-1">Selecione...</option>
                    </select>
                }
                <span asp-validation-for="VersaoId"></span>

            </div>
        </div>
    </div>

    <br />
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label>Ano</label>
                <input class="form-control" type="text" asp-for="Ano" placeholder="Ano" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Quilômetragem </label>
                <input class="form-control" type="text" asp-for="Quilometragem" placeholder="Quilômetragem" />
                <span asp-validation-for="Quilometragem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Observação</label>
                <input class="form-control" type="text" asp-for="Observacao" placeholder="Observação" />
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>
        </div>
    </div>
    
    <input type="submit" value="Cadastrar" class="btn btn-success" style="float:right; margin-left:10px;" />
    <a href="@Url.Action("Index", "Anuncio")" class="btn btn-danger" style="float:right">Cancelar </a>

    <input type="hidden" id="Marca" asp-for="Marca" />
    <input type="hidden" id="Modelo" asp-for="Modelo" />
    <input type="hidden" id="Versao" asp-for="Versao" />


</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMotors/source/WebMotors.Web/Views/Anuncio/Index.cshtml
@model List<Anuncio>
@if (Model != null)
{
    <div class="row">
        <div class="col-md-12">
            <h1>Meus Anúncios</h1>
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Cadastrar", "Anuncio")" class="btn btn btn-primary" style="float: right;">Novo Anúncio</a>
        </div>
    </div>
    <br />
    <br />
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Marca</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Versâo</th>
                        <th scope="col">Ano</th>
                        <th scope="col">Quilometragem</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Marca)</td>
                            <td>@Html.DisplayFor(modelItem => item.Modelo)</td>
                            <td>@Html.DisplayFor(modelItem => item.Versao)</td>
                            <td>@Html.DisplayFor(modelItem => item.Ano)</td>
                            <td>@Html.DisplayFor(modelItem => item.Quilometragem)</td>
                            <td>
                                <a href="@Url.Action("Atualizar", "Anuncio", new {id=item.Id })" class="btn btn btn-primary" style="float: right;">Atualizar</a> |
                                <a href="@Url.Action("Remover", "Anuncio", new {id=item.Id })" class="btn btn btn-danger" style="float: right; margin-right: 10px;">Deletar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <h5>Nenhum resultado encontrado.</h5>
}

WebMotors/source/WebMotors.Web/Views/Anuncio/Remover.cshtml
@model Anuncio

@{
    ViewData["Title"] = "Remover Anúncio";
}

<h1>Remover Anúncio</h1>
<hr />

@Html.ValidationSummary(false)

@if (Model != null)
{
    <div class="row">
        <div class="col-md-4">
            <label>
                Marca
            </label>
            <span class="badge badge-primary">@Model.Marca</span>
        </div>
        <div class="col-md-4">
            <label>
                Modelo
            </label>
            <span class="badge badge-primary">@Model.Modelo</span>
        </div>
        <div class="col-md-4">
            <label>
                Versão
            </label>
            <span class="badge badge-primary">@Model.Versao</span>
        </div>
    </div>
    <br />
    <br />

    <div class="row">
        <div class="col-md-12">
            <h2>Tem certeza que deseja remover o anúncio ?</h2>
        </div>
    </div>
    <br />

    <div class="row">
        <form asp-action="Remover" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary" value="Remover" style="float:right;" />
                <a href="@Url.Action("Index", "Anuncio")" class="btn btn-success" style="float:right; margin-right:10px; ">Cancelar</a>
            </div>
        </form>
    </div>
}
else
{
    <h5>Anúncio não encontrado.</h5>
}

WebMotors/source/WebMotors.Web/Views/Anuncio/View.cshtml
@model WebMotors.Core.Entidades.Anuncio

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>AnuncioRepository</h4>
<hr />
<div class="row">


    <select asp-for="MarcaId"
            asp-items="ViewBag.ListaDeMarcas">
    </select>

    <select asp-for="ModeloId">
        <option value="-1">Selecione...</option>
    </select>

    <select asp-for="VersaoId">
        <option value="-1">Selecione...</option>
    </select>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMotors/source/WebMotors.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo</h1>
    <p>Teste WebMotors</p>
</div>

WebMotors/source/WebMotors.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMotors</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMotors</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anuncio" asp-action="Index">Meus Anúncios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebMotors - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>